# Generated by Django 4.2.29 on 2026-05-30 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='产品类型名称')),
            ],
            options={
                'verbose_name': '产品类型',
                'verbose_name_plural': '产品类型',
            },
        ),
        migrations.CreateModel(
            name='CooperateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_title', models.CharField(max_length=120, verbose_name='计划标题')),
                ('plan_content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='详细图文内容')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '合作开发计划',
                'verbose_name_plural': '合作开发计划',
            },
        ),
        migrations.CreateModel(
            name='DevDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='文档标题')),
                ('introduce', models.TextField(blank=True, verbose_name='文档简介')),
                ('doc_file', models.FileField(upload_to='file_docs/', verbose_name='上传文档文件')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '开发者文档',
                'verbose_name_plural': '开发者文档',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='DevTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=120, verbose_name='工具包名称')),
                ('version', models.CharField(max_length=40, verbose_name='版本号')),
                ('tool_desc', models.TextField(verbose_name='工具介绍')),
                ('tool_zip', models.FileField(upload_to='file_tools/', verbose_name='上传压缩包')),
                ('release_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '开发工具包',
                'verbose_name_plural': '开发工具包',
                'ordering': ['-release_time'],
            },
        ),
        migrations.CreateModel(
            name='HotCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='车型名称')),
                ('cover_image', models.ImageField(upload_to='hotcar_covers/', verbose_name='封面图')),
                ('short_desc', models.CharField(max_length=200, verbose_name='简短简介')),
                ('detail_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='图文详情')),
                ('sort', models.IntegerField(default=0, verbose_name='排序号（数字越小越靠前）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架/热推')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '热推车型',
                'verbose_name_plural': '热推车型',
                'ordering': ['sort', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='资讯标题')),
                ('summary', models.TextField(blank=True, verbose_name='简短简介')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='详细内容')),
                ('img', models.ImageField(blank=True, null=True, upload_to='news_cover/', verbose_name='资讯封面图片')),
                ('is_top_news', models.BooleanField(default=False, verbose_name='设为顶部最新时讯(轮播)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '资讯管理',
                'verbose_name_plural': '资讯管理',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='用户头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('brand', models.CharField(max_length=50, verbose_name='品牌')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('img_url', models.ImageField(blank=True, null=True, upload_to='trucks/product/', verbose_name='产品上传图片')),
                ('intro', models.TextField(blank=True, verbose_name='介绍')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trucks.category', verbose_name='产品类型')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
    ]
