# Generated by Django 4.2.29 on 2026-05-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_audited',
            field=models.BooleanField(default=False, verbose_name='是否审核通过'),
        ),
    ]
