# Generated by Django 4.2.29 on 2026-05-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_is_audited'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='置顶帖子'),
        ),
    ]
