"""
Django settings for mysite1 project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'm6=&kn*bsp^(6+5hxe=93=6b%a_lh_68)so$=(=sn3-d48c%ex'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#启动模式
#Ture - 调试模式
#False - 正式启动模式 / 上线模式
#1，检测代码改动后，立刻重启
#2，报错页面



ALLOWED_HOSTS = []
#请求头Host头,也就是域名

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'trucks',
    'django_ckeditor_5',
    'forum',
    'django_crontab',
    'rbac',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'mysite1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'trucks', 'templates', 'trucks'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'truck_website',  # 刚创建的数据库名
        'USER': 'root',           # MySQL 用户名
        'PASSWORD': '123456',     # 你刚设置的 MySQL 密码
        'HOST': '127.0.0.1',      # 本地地址
        'PORT': '3306',           # MySQL 默认端口
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

LANGUAGES = [
    ('zh-hans', '简体中文'),
    ('en', 'English'),
]

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
#静态文件配置
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'trucks/static'),
]


# 媒体文件配置（必须加，否则图片上传不生效）
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' 

# CKEditor上传配置
# ---------- 删掉你原来所有CKEditor相关配置，替换成下面这一段 ----------
# CKEditor 5 完整配置（直接复制）
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'undo', 'redo', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'link', 'uploadImage', '|',  # 必须有uploadImage，才会显示上传按钮
            'bulletedList', 'numberedList', 'blockQuote', '|',
            'insertTable', '|',
            'sourceEditing'
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative', '|',
                'imageStyle:alignLeft', 'imageStyle:alignCenter', 'imageStyle:alignRight',
                '|',
                'resizeImage'
            ],
        },
        'language': 'zh-cn',
        'height': 400,
    }
}

# CKEditor 5 图片上传路径
CKEDITOR_5_UPLOAD_PATH = "ckeditor5_uploads/"
# 登录配置
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/login/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# 每日0点自动任务
CRONJOBS = [
    # 1. 0点整：重置所有用户下载次数
    ('0 0 * * *', 'django.core.management.call_command', ['reset_download_counts']),
    # 2. 0点05分：自动降级90天未登录用户
    ('5 0 * * *', 'django.core.management.call_command', ['auto_downgrade']),
]