# Generated by Django 4.2.29 on 2026-05-19 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm_name', models.CharField(max_length=30, verbose_name='权限名称')),
                ('perm_code', models.CharField(max_length=50, unique=True, verbose_name='权限标识')),
            ],
            options={
                'verbose_name': '功能权限',
                'verbose_name_plural': '功能权限',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=20, verbose_name='角色名称')),
                ('desc', models.CharField(blank=True, max_length=100, verbose_name='角色说明')),
            ],
            options={
                'verbose_name': '系统角色',
                'verbose_name_plural': '系统角色',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(0, '游客'), (1, '普通用户'), (2, '普通会员'), (3, '超级会员'), (4, '至尊会员')], default=1, verbose_name='用户等级')),
                ('avatar_frame', models.CharField(blank=True, max_length=200, verbose_name='专属头像框地址')),
                ('active_time', models.IntegerField(default=0, verbose_name='累计活跃时长')),
                ('post_num', models.IntegerField(default=0, verbose_name='累计发帖数')),
                ('like_num', models.IntegerField(default=0, verbose_name='累计获赞数')),
                ('comment_num', models.IntegerField(default=0, verbose_name='累计评论数')),
                ('last_login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后登录时间')),
                ('violate_count', models.IntegerField(default=0, verbose_name='违规次数')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL, verbose_name='关联账号')),
            ],
            options={
                'verbose_name': '用户会员资料',
                'verbose_name_plural': '用户会员资料',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.role', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户绑定角色',
                'verbose_name_plural': '用户绑定角色',
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='RolePerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.permission', verbose_name='权限')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色绑定权限',
                'verbose_name_plural': '角色绑定权限',
                'unique_together': {('role', 'perm')},
            },
        ),
    ]
