# Generated by Django 4.2.29 on 2026-05-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_userinfo_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='total_activity',
            field=models.IntegerField(default=0, verbose_name='总活跃度'),
        ),
    ]
